apiVersion: skaffold/v2beta25
kind: Config
build:
    artifacts:
        - image: gcr.io/qwiklabs-gcp-02-5b814546322d/source-vm
          context: ./
          docker:
            dockerfile: Dockerfile
deploy:
    kubectl:
        manifests:
            - ./deployment_spec.yaml
profiles:
    - name: cloudbuild
      build:
        googleCloudBuild:
            timeout: 3600s
            logStreamingOption: STREAM_OFF
