gcs:
  enabled: true
  bucket: qwiklabs-gcp-00-590ac91686ca-spinnaker-config
  project: qwiklabs-gcp-00-590ac91686ca
  jsonKey: '{}'
dockerRegistries:
- name: gcr
  address: https://gcr.io
  username: _json_key
  password: '{}'
  email: 1234@5678.com
# Disable minio as the default storage backend
minio:
  enabled: false
# Configure Spinnaker to enable GCP services
halyard:
  spinnakerVersion: 1.19.4
  image:
    repository: us-docker.pkg.dev/spinnaker-community/docker/halyard
    tag: 1.32.0
    pullSecrets: []
  additionalScripts:
    create: true
    data:
      enable_gcs_artifacts.sh: |-
        $HAL_COMMAND config artifact gcs account add gcs-qwiklabs-gcp-00-590ac91686ca --json-path /opt/gcs/key.json
        $HAL_COMMAND config artifact gcs enable
      enable_pubsub_triggers.sh: |-
        $HAL_COMMAND config pubsub google enable
        $HAL_COMMAND config pubsub google subscription add gcr-triggers           --subscription-name gcr-triggers           --json-path /opt/gcs/key.json           --project qwiklabs-gcp-00-590ac91686ca           --message-format GCR
